baseurl: "/"
languageCode: "en-us"
theme: "hugo-xmin"
title: "Asutosh Panda"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "â†©"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: Been There Done That
      url: "/been-there-done-that/"
      weight: 2
    - name: Students
      url: "/students/"
      weight: 3


# params:
#   description: "A website built through Hugo and blogdown."
#   footer: "&copy; [Yihui Xie](https://yihui.org) 2017 -- {Year} | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
